/**
 * Bible meta for Study browse (66 books). Chapter counts are canonical Protestant canon.
 * genre: Poetry | History | Prophecy | Law | Wisdom | Gospel | Epistle | Apocalyptic
 */
(function (global) {
  var B = [
    ['Genesis', 50, 'ot', 'History'],
    ['Exodus', 40, 'ot', 'Law'],
    ['Leviticus', 27, 'ot', 'Law'],
    ['Numbers', 36, 'ot', 'History'],
    ['Deuteronomy', 34, 'ot', 'Law'],
    ['Joshua', 24, 'ot', 'History'],
    ['Judges', 21, 'ot', 'History'],
    ['Ruth', 4, 'ot', 'History'],
    ['1 Samuel', 31, 'ot', 'History'],
    ['2 Samuel', 24, 'ot', 'History'],
    ['1 Kings', 22, 'ot', 'History'],
    ['2 Kings', 25, 'ot', 'History'],
    ['1 Chronicles', 29, 'ot', 'History'],
    ['2 Chronicles', 36, 'ot', 'History'],
    ['Ezra', 10, 'ot', 'History'],
    ['Nehemiah', 13, 'ot', 'History'],
    ['Esther', 10, 'ot', 'History'],
    ['Job', 42, 'ot', 'Wisdom'],
    ['Psalms', 150, 'ot', 'Poetry'],
    ['Proverbs', 31, 'ot', 'Wisdom'],
    ['Ecclesiastes', 12, 'ot', 'Wisdom'],
    ['Song of Songs', 8, 'ot', 'Poetry'],
    ['Isaiah', 66, 'ot', 'Prophecy'],
    ['Jeremiah', 52, 'ot', 'Prophecy'],
    ['Lamentations', 5, 'ot', 'Poetry'],
    ['Ezekiel', 48, 'ot', 'Prophecy'],
    ['Daniel', 12, 'ot', 'Prophecy'],
    ['Hosea', 14, 'ot', 'Prophecy'],
    ['Joel', 3, 'ot', 'Prophecy'],
    ['Amos', 9, 'ot', 'Prophecy'],
    ['Obadiah', 1, 'ot', 'Prophecy'],
    ['Jonah', 4, 'ot', 'Prophecy'],
    ['Micah', 7, 'ot', 'Prophecy'],
    ['Nahum', 3, 'ot', 'Prophecy'],
    ['Habakkuk', 3, 'ot', 'Prophecy'],
    ['Zephaniah', 3, 'ot', 'Prophecy'],
    ['Haggai', 2, 'ot', 'Prophecy'],
    ['Zechariah', 14, 'ot', 'Prophecy'],
    ['Malachi', 4, 'ot', 'Prophecy'],
    ['Matthew', 28, 'nt', 'Gospel'],
    ['Mark', 16, 'nt', 'Gospel'],
    ['Luke', 24, 'nt', 'Gospel'],
    ['John', 21, 'nt', 'Gospel'],
    ['Acts', 28, 'nt', 'History'],
    ['Romans', 16, 'nt', 'Epistle'],
    ['1 Corinthians', 16, 'nt', 'Epistle'],
    ['2 Corinthians', 13, 'nt', 'Epistle'],
    ['Galatians', 6, 'nt', 'Epistle'],
    ['Ephesians', 6, 'nt', 'Epistle'],
    ['Philippians', 4, 'nt', 'Epistle'],
    ['Colossians', 4, 'nt', 'Epistle'],
    ['1 Thessalonians', 5, 'nt', 'Epistle'],
    ['2 Thessalonians', 3, 'nt', 'Epistle'],
    ['1 Timothy', 6, 'nt', 'Epistle'],
    ['2 Timothy', 4, 'nt', 'Epistle'],
    ['Titus', 3, 'nt', 'Epistle'],
    ['Philemon', 1, 'nt', 'Epistle'],
    ['Hebrews', 13, 'nt', 'Epistle'],
    ['James', 5, 'nt', 'Epistle'],
    ['1 Peter', 5, 'nt', 'Epistle'],
    ['2 Peter', 3, 'nt', 'Epistle'],
    ['1 John', 5, 'nt', 'Epistle'],
    ['2 John', 1, 'nt', 'Epistle'],
    ['3 John', 1, 'nt', 'Epistle'],
    ['Jude', 1, 'nt', 'Epistle'],
    ['Revelation', 22, 'nt', 'Apocalyptic']
  ];
  global.STUDY_BIBLE_BOOKS = B.map(function (r) {
    return { name: r[0], chapters: r[1], testament: r[2], genre: r[3] };
  });
})(typeof window !== 'undefined' ? window : this);
